### ISSUE TITLE
Autoplay not working

### ISSUE THREAD

**Issue by yasirrose** [musocrat/jquery-video-lightning#15] opened 2015-09-23 18:38 UTC
Setting `autoplay` to `true` doesn't cause the video to `autoplay`.

**Comment by musocrat** [comment] 2015-09-24 01:36
I think I may know what the problem is and I'm afraid the docs aren't clear on this one. Correct me if this is not the issue.

As it is implemented "autoplay" is not truly an auto-playback. At least not on page load. Basically that controls the Youtube / Vimeo "autoplay" option. So if it were false when a user clicks the element to open the lightbox it will be in a paused state at the beginning of the video and will require the user to click the play button to start playing. If true when the element is clicked it should start playing.

So that is the expected behavior at this point. Does that align with what you are experiencing or is it not playing after the element is clicked?

**Comment by musocrat** [comment] 2015-09-29 22:27
I'm going to close this based on the above assumption that the autoplay feature is functioning as designed, though perhaps not as expected. The readme has been updated to reflect the expected behavior.

If my above assumptions were incorrect feel free to comment back and re-open the issue.

**Closed by musocrat** 2015-09-29 22:27 UTC
